import { createClient } from '@supabase/supabase-js'

export const supabase = createClient('https://actveysuzoclardagmsk.supabase.co', 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFjdHZleXN1em9jbGFyZGFnbXNrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzI0NzQxMzMsImV4cCI6MjA0ODA1MDEzM30.kVE5l_2jHFlGu_u1EzEPaa6VQP1LR3JC7wMpSayPIMs')